markdown: kramdown
permalink: /:year/:month/:title/
baseurl: /blog
highlighter : rouge
exclude: ["node_modules", "sandbox", "blog.iml", "Gem*", "Gruntfile.js", "package.json", "README.md"]
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap